### PR TITLE
CPP Debug

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
Or `FFTW3_LIBS="-L${PREFIX}/lib -lfftw3 -lfftw3f"` ?

**Comment by jmbeuken** [comment]
👍

**Comment by jan-janssen** [comment]
I do not see any `FCFLAGS` in the conda environment: 
```
2020-06-05T11:38:48.1886088Z +ADDR2LINE=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-addr2line
2020-06-05T11:38:48.1886995Z +AR=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-ar
2020-06-05T11:38:48.1887605Z +AS=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-as
2020-06-05T11:38:48.1888391Z +CXXFILT=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-c++filt
2020-06-05T11:38:48.1889029Z +ELFEDIT=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-elfedit
2020-06-05T11:38:48.1889575Z +GPROF=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-gprof
2020-06-05T11:38:48.1890309Z +HOST=x86_64-conda_cos6-linux-gnu
2020-06-05T11:38:48.1890885Z +LD_GOLD=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-ld.gold
2020-06-05T11:38:48.1900715Z +LD=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-ld
2020-06-05T11:38:48.1901735Z +NM=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-nm
2020-06-05T11:38:48.1902477Z +OBJCOPY=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-objcopy
2020-06-05T11:38:48.1903393Z +OBJDUMP=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-objdump
2020-06-05T11:38:48.1904151Z +RANLIB=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-ranlib
2020-06-05T11:38:48.1905465Z +READELF=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-readelf
2020-06-05T11:38:48.1906167Z +SIZE=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-size
2020-06-05T11:38:48.1906879Z +STRINGS=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-strings
2020-06-05T11:38:48.1907557Z +STRIP=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-strip
2020-06-05T11:38:48.3018197Z INFO: activate-gcc_linux-64.sh made the following environmental changes:
2020-06-05T11:38:48.3051578Z +CC=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-cc
2020-06-05T11:38:48.3052846Z +CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/abinit-9.0.4 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
2020-06-05T11:38:48.3053862Z +CMAKE_PREFIX_PATH=$PREFIX:$BUILD_PREFIX/x86_64-conda_cos6-linux-gnu/sysroot/usr
2020-06-05T11:38:48.3054530Z +CONDA_BUILD_SYSROOT=$BUILD_PREFIX/x86_64-conda_cos6-linux-gnu/sysroot
2020-06-05T11:38:48.3055219Z +_CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
2020-06-05T11:38:48.3055749Z +CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include
2020-06-05T11:38:48.3056347Z +CPP=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-cpp
2020-06-05T11:38:48.3057416Z +DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/abinit-9.0.4 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
2020-06-05T11:38:48.3058366Z +DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -isystem $PREFIX/include
2020-06-05T11:38:48.3058984Z +GCC_AR=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-gcc-ar
2020-06-05T11:38:48.3059558Z +GCC=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-gcc
2020-06-05T11:38:48.3060112Z +GCC_NM=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-gcc-nm
2020-06-05T11:38:48.3060705Z +GCC_RANLIB=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-gcc-ranlib
2020-06-05T11:38:48.3061507Z +LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib
2020-06-05T11:38:48.4078485Z INFO: activate-gfortran_linux-64.sh made the following environmental changes:
2020-06-05T11:38:48.4115409Z +DEBUG_FFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/abinit-9.0.4 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments -ffunction-sections -pipe
2020-06-05T11:38:48.4122080Z +DEBUG_FORTRANFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/abinit-9.0.4 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments -ffunction-sections -pipe
2020-06-05T11:38:48.4126844Z +F77=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-gfortran
2020-06-05T11:38:48.4131422Z +F90=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-gfortran
2020-06-05T11:38:48.4132313Z +F95=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-f95
2020-06-05T11:38:48.4133053Z +FC=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-gfortran
2020-06-05T11:38:48.4134593Z +FFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/abinit-9.0.4 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
2020-06-05T11:38:48.4136117Z +FORTRANFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/abinit-9.0.4 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
2020-06-05T11:38:48.4137134Z +GFORTRAN=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-gfortran
2020-06-05T11:38:48.4524964Z INFO: activate-gxx_linux-64.sh made the following environmental changes:
2020-06-05T11:38:48.4556099Z +CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/abinit-9.0.4 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
2020-06-05T11:38:48.4560291Z +CXX=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-c++
2020-06-05T11:38:48.4561760Z +DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/abinit-9.0.4 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
2020-06-05T11:38:48.4562793Z +GXX=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-g++
```

**Comment by jan-janssen** [comment]
It seems like the `FCFLAGS` are note set in conda build. Still I merge this PR to see if it fixes the bug.

**Comment by jmbeuken** [comment]
ok...  I understand why it works : 

in `./configure`, there is  

```
grep FFLAGS configure
ac_subst_vars='FFLAGS
FFLAGS="${FCFLAGS}"
```

the problem "Program received signal SIGILL: Illegal instruction."  probably comes from
`-mtune=X -march=Y`

**Pull request merged**
